-- Seed: cele 30 de locatii (14 centre + 16 apartamente) importate din caminromantic.com/profile
-- Ruleaza DUPA 0001_init.sql

insert into public.centers (nume, cod, tip, cladire, adresa, localitate, judet, capacitate) values
  ('CZ Mihai Bravu', 'CZ', 'centru', NULL, 'Str Motilor 16', 'Sector 3', 'București', '50'),
  ('ALEX SOCIAL', NULL, 'centru', NULL, 'Strada Moțiolor nr 16, Etaj 4', 'Sector 3', 'București', '1'),
  ('CABR Argedava', 'CAbR', 'centru', NULL, 'Calea Bucuresti 335', 'Mihăilești', 'Giurgiu', '30'),
  ('CIA Casa cu Tei', 'CIA', 'centru', NULL, 'Str. Dacia Nr 152A, Sat Popesti', 'Mihăilești', 'Giurgiu', '50'),
  ('CIA Romantic', 'CIA', 'centru', NULL, 'Str. Dacia nr. 154, Sat Popești', 'Mihăilești', 'Giurgiu', '42'),
  ('EM Mihai Bravu', 'EM', 'centru', NULL, 'Str Motilor 16, Etaj 3', 'Sector 3', 'București', '100'),
  ('LMP 1 Ateneul Roman', 'LP', 'centru', NULL, 'Str. Episcopiei nr 6, et 1, ap 1', 'Sector 1', 'București', '10'),
  ('LMP Stefan cel Mare', 'LP', 'centru', NULL, 'Bdl Stefan Cel Mare 39', 'Sector 2', 'București', '7'),
  ('LP4 BRÂNCOVEANU', NULL, 'centru', NULL, 'Strada Dâmbului nr 74, bl C, Ap4, Parter', NULL, 'București', '4'),
  ('SID Vârstnici', NULL, 'centru', NULL, 'Str. Moților 16', 'Sector 3', 'București', '40'),
  ('SAS Mihai Bravu', 'SAS', 'centru', NULL, 'str Moților nr 16', 'Sector 3', 'București', '60'),
  ('SID Dizabilităţi Mihai Bravu', 'SID', 'centru', NULL, 'Str Motilor 16, Etaj 3', 'Sector 3', 'București', '100'),
  ('Symphony', NULL, 'centru', NULL, 'Str Sergent Ilie Petre, Nr. 86, camera 1, Bloc 1, etaj 1, ap 114', 'Comuna Chiajna', 'Ilfov', '1'),
  ('Test Center', 'CIA', 'centru', NULL, 'Test', NULL, 'București', '60'),
  ('LMP Pantelimon 1', 'CPVI', 'apartament', 'Bl. D19 - Str. Delfinului 11', 'Str. Delfinului nr. 11, Bl. D19', 'Sector 2', 'București', '7'),
  ('LMP Pantelimon 2', 'CPVI', 'apartament', 'Bl. D19 - Str. Delfinului 11', 'Str. Delfinului nr. 11, Bl. D19', 'Sector 2', 'București', '7'),
  ('LMP Pantelimon 4', 'CPVI', 'apartament', 'Bl. D19 - Str. Delfinului 11', 'Str. Delfinului nr. 11, Bl. D19', 'Sector 2', 'București', '7'),
  ('LMP Mihai Bravu 101', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 1, ap 101', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 104', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 1, ap 104', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 201', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 2, ap 201', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 209', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 2, ap 209', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 303', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 3, ap 303', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 305', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 3, ap 305', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 309', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 3, ap 309', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 416', 'LP', 'apartament', 'Bl. VE1 - Intrarea Monolitului 23-31', 'Str. Intrarea Monolitului 23-31, bl VE1, et 4, ap 416', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 303N', 'LP', 'apartament', 'Bl. VE2 - Str. Moților 20C', 'Str. Moților nr 20C, Ap 303N, Etaj 3, Bl.VE2', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 403N', 'LP', 'apartament', 'Bl. VE2 - Str. Moților 20C', 'Str. Moților nr 20C, Ap 403N, Etaj 4, Bl.VE2', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 502S', NULL, 'apartament', 'Bl. VE2 - Str. Moților 20C', 'Str. Moților nr 20C, Ap 503N, Etaj 5, Bl.VE2', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 507S', NULL, 'apartament', 'Bl. VE2 - Str. Moților 20C', 'Str. Moților nr 20C, Ap 507S, Etaj 5, Bl.VE2', 'Sector 3', 'București', '4'),
  ('LMP Mihai Bravu 607N', 'LP', 'apartament', 'Bl. VE2 - Str. Moților 20C', 'Str. Moților nr 20C, Ap 607N, Etaj 6, Bl.VE2', 'Sector 3', 'București', '4')
on conflict (nume) do nothing;
