-- Seed: cei 181 de angajati importati din caminromantic.com/profile
-- Ruleaza DUPA 0001_init.sql si 0002_seed_centers.sql

insert into public.employees (nume, functie, email, telefon, este_salariat, activ) values
  ('Alan Altonchi', 'Admin', 'alanaltonchi@hotmail.com', '0774273134', true, true),
  ('Andreescu Andrei-Vlad', 'Supervizor', 'andreescuandrei190@gmail.com', '0727806421', true, true),
  ('Andreescu Cristina Firma Contabila', 'Contabil', 'cristinaangelaandreescu2003@gmail.com', NULL, true, true),
  ('Argeșeanu Cristina Georgiana', 'Lucrător Social', 'cristinaargeseanu.ca@gmail.com', '0734602171', true, true),
  ('Arsene Elena', 'Infirmieră', 'testarsene@gmail.com', '0735134337', true, true),
  ('Badea Andreea Luciana', 'Infirmieră', 'lucianabadea75@gmail.com', '0761551605', true, true),
  ('Badea Danut', 'Lucrător Social', 'testbadea@gmail.com', '0736694353', true, true),
  ('Badea Laurentia Cristiana', 'Asistent Medical Generalist', 'badeamaria420@gmail.com', '0723398574', true, true),
  ('Banu Niculaie', 'Lucrător Social', 'banuniculaie64@gmail.com', '0790293190', true, true),
  ('Barb-Dudan Felicia-Sector 3', 'Asistent Social', 'f.georgiana23@yahoo.com', '0729330355', false, true),
  ('Belghiru Roxana', 'Asistent medical sef', 'roxanabelghiru@gmail.com', '0764506372', true, true),
  ('Bici Maria', 'Infirmieră', 'bicimariana128@gmail.com', '0732173163', true, true),
  ('Blănaru Alin Cristian', 'Terapeut Ocupațional', 'alincristian1201@gmail.com', '0769583113', true, true),
  ('Bogdan Marian-Viorel', 'Lucrator social', 'mariantest@gmail.com', NULL, true, true),
  ('Boșman Petronela', 'INFIRMIERA', 'petronelabosman@gmail.com', '0731620115', true, true),
  ('Burcea Gabriela', 'Infirmieră', 'burceagabriela43@gmail.com', '0765158491', true, true),
  ('Burtavel Ionel', 'Lucrător Social', 'ionelburtavel20@gmail.com', NULL, true, true),
  ('Buzică Doinița', 'Îngrijitoare la Unitățile de Ocrotire Socială și Sanitară', 'buzicadoinita1@gmail.com', '0724565533', true, true),
  ('Bîrlan Viorica', 'Bucătar', 'birlanviorica@gmail.com', '0784860530', true, true),
  ('Caimacanu Leana Iuliana', 'Infirmieră', 'liliana@gmail.com', NULL, true, true),
  ('Calea Catalin Ionut', 'Lucrător Social', 'calea7@gmail.com', '0733570751', true, true),
  ('Calin Rodica', 'infirmiera', 'rodicacalin2017@gmail.com', '0791490050', true, true),
  ('Chiripuci Constanta', 'Bucătar', 'chiripucitanta@gmail.com', '0762722239', true, true),
  ('Chițu Gabriela-Raluca', 'Bucătar', 'ralucachitu1214@gmail.com', '0766923428', true, true),
  ('Ciocan Mihaela', 'Infirmieră', 'miki27031968@gmail.com', '0721284170', true, true),
  ('Ciocoiu Elena Florenta', 'Infirmieră', 'elenaflorentaciocoiu@gmail.com', '0725211926', true, true),
  ('Cirstea Elena Georgiana', 'Ergoterapeut', 'cridfllo@gmail.com', '0768927737', true, true),
  ('Ciulei Mitana Niculina', 'Infirmieră', 'ciulei@gmail.com', '0761275491', true, true),
  ('Ciumber Steluța', 'Infirmieră', 'ciumbersteluta06@gmail.com', '0723978703', true, true),
  ('Claudia Ungureanu', 'Admin', 'caminromanticclub@gmail.com', '0769665173', true, true),
  ('Constantin Elena Cristina', 'Secretara', 'elenacristina2112@gmail.com', '0785311440', true, true),
  ('Cosoi Iuliana Valentina', 'Terapeut Ocupațional', 'iulianacosoi@gmail.com', '0775318827', true, true),
  ('Cosovliu Nicoleta', 'Infirmieră', 'ncosovliu@gmail.com', '0722481412', true, true),
  ('Costache Gabriel', 'Lucrător Social', 'TESTCOSTACHEGABRIEL@GMAIL.COM', NULL, true, true),
  ('Creangă Nicoleta Cristina', 'Asistent Social', 'cristinacreanga499@yahoo.com', '0764361439', true, true),
  ('Crețu Constantin', 'Lucrator Social', 'valicretu66@gmail.com', '0720486808', true, true),
  ('Crețu Irina', 'Infirmieră', 'irinacretu591@gmail.com', '(0720) 076 566', true, true),
  ('Cîrstea Elena-Dgaspc Gorj', 'Asistent Social', 'cirstea_elena2000@yahoo.com', '0768941807', false, true),
  ('Căpitanu Mariana Nicoleta', 'Infirmieră', 'capitanumariana903@gmail.com', '0787634618', true, true),
  ('Daia Gina', 'Infirmieră', 'daiagina71@gmail.com', '0760533925', true, true),
  ('Debretin Denisa', 'Terapeut Ocupațional', 'karinna2924@gmail.com', '0732443423', true, true),
  ('Dinu Daniela Ionela', 'Asistent Medical', 'voineadaniela2010@gmail.com', '0771338306', true, true),
  ('Dinu Georgeta', 'INFIRMIERA', 'georgetadinu906@gmail.com', '0763732593', true, true),
  ('Dinulescu Ileana', 'Asistent Medical Generalist', 'ileanadinulescu71@gmail.com', '0761345834', true, true),
  ('Dogaru Alexandra Denisa', 'Infirmieră', 'alexandra.dogaru12@gmail.com', '0787573142', true, true),
  ('Draganescu Cristina Mirela', 'Terapeut Ocupational', 'Bvy05920@gmail.com', '0770346219', true, true),
  ('Draghia Liliana', 'Infirmieră', 'bogdanbrotacel@gmail.com', '0733945397', true, true),
  ('Dragomir Iuliana Arabela', 'Asistent medical generalist', 'iulianadragomir478@gmail.com', '0722399416', true, true),
  ('Drăgănescu Cristian', 'LUCRĂTOR SOCIAL', 'bxc5599@gmail.com', '0773957725', true, true),
  ('Dumitrache Doru', 'Lucrător Social', 'dumitrachetest@gmail.com', '0771697403', true, true),
  ('Dumitru Doina', 'Maseur', 'enacheilona13@gmail.com', '0786643146', true, true),
  ('Dumitru Ilie', 'Lucrător Social', 'id080511@gmail.com', '0739943198', true, true),
  ('Dumitru Marius Alin', 'Terapeut Ocupational', 'alinm9429@gmail.com', '0768755411', true, true),
  ('Dumitru Smaranda Marcela', 'Bucătar', 'dumitrusmarandamarcela@gmail.com', '0727698440', true, true),
  ('Ene Anișoara', 'Infirmieră', 'eneanisoara5@gmail.com', '0727516380', true, true),
  ('Ene Daniela', 'Ergoterapeut', 'danielapietris1@gmail.com', '0770136096', true, true),
  ('Enus Mihai', 'Lucrator social', 'mihaitaenus95@gmail.com', '0726968745', true, true),
  ('Filip Georgiana Elena-Dgaspc S2', 'Asistent Social', 'georgiana.filip@social2.ro', '0752064173', false, true),
  ('Florescu Cristina', 'TEHNICIAN ASISTENT SOCIAL', 'cristinabolboasa8@gmail.com', '0769913103', true, true),
  ('Friptu Doina', 'TEHNICIAN ZOOTEHNIST', 'doinafriptu869@gmail.com', '0765401337', true, true),
  ('Friptu Fanel', 'Lucrator social', 'friptufane16@gmail.com', '0734316667', true, true),
  ('Friptu Georgiana Denisa', 'Infirmieră', 'friptumirel@yahoo.com', '0787884882', true, true),
  ('Friptu Marius Bogdan', 'Lucrător Social', 'friptumarius1410@gmail.com', '0726624687', true, true),
  ('Făinaru Anișoara', 'Îngrijitoare la Unitățile de Ocrotire Socială și Sanitară', 'anisoarafainaru@gmail.com', '0727068486', true, true),
  ('Garaliu Andreea', 'Îngrijitor', 'garaliuandreea70@gmail.com', '0775274686', true, true),
  ('Gheorghe Remus', 'Lucrător Social', 'gheorghetest@gmail.com', '0761703916', true, true),
  ('Gherasim Violeta', 'Infirmieră', 'gherasimvioleta1111@gmail.com', '0736681108', true, true),
  ('Ghiulea Petra', 'Infirmieră', 'ghiulea.petra@gmail.com', '0787816997', true, true),
  ('Grama Adriana', 'TERAPEUT OCUPATIONAL', 'adrianagrama667@gmail.com', '0724639301', true, true),
  ('Graure Alexandra', 'Asistent medical', 'alexaagraure@gmail.com', '0766629238', true, true),
  ('Grindean Elena Camelia', 'Infirmieră', 'elenacameliagrindean3@gmail.com', '0753121738', true, true),
  ('Gudină Maria', 'Infirmiera', 'gudina.maria68@gmail.com', '0764709384', true, true),
  ('Iancu Georgiana-Marina', 'Terapeut Ocupațional', 'georgianamarina35@gmail.com', '0761860680', true, true),
  ('Iancu Ionut', 'Terapeut Sef', 'ionutiancu19866@gmail.com', '0790555454', true, true),
  ('Iofcea Maria', 'Infirmieră', 'iofceamariamagdalena@gmail.com', '0761667278', true, true),
  ('Iofcea Valentin', 'Lucrător Social', 'iofceatest@gmail.com', '0746071843', true, true),
  ('Ion Alexandra Florentina', 'Infirmieră', 'ionalexandra645@gmail.com', '0785087096', true, true),
  ('Ion Florina', 'Infirmieră', 'florina.ivan2226@gmail.com', '0738315916', true, true),
  ('Ion Nuti Geanina', 'Terapeut Ocupational', 'Iongeanina969@gmail.com', '0784484846', true, true),
  ('Ivan Aurica', 'Infirmieră', 'ivan@gmail.com', NULL, true, true),
  ('Ivan Grațiela Elena', 'Asistent Social', 'gratiela11ivan@gmail.com', '0729607726', true, true),
  ('Leană Ionela', 'Lucrator social', 'danielaileana221@gmail.com', '0730839028', true, true),
  ('Lemăndroi Mihai', 'Lucrător Social', 'mihai01lemandroi@gmail.com', '0724177438', true, true),
  ('Lepădatu Alexandra', 'Infirmieră', 'lepadatusanda815@gmail.com', '0768007308', true, true),
  ('Lincu Gabriela Elena', 'PSIHOLOG', 'lincugabrielaelena@gmail.com', '0760903754', true, true),
  ('Lupu Catalin', 'Asistent social', 'lupucatalin08@gmail.com', '0731776631', true, true),
  ('Lăcătușu Mihaela', 'Asistent Medical Generalist', 'vanessa.maria231998@gmail.com', '0769372528', true, true),
  ('Macavei Floarea', 'Infirmieră', 'mfloarea676@gmail.com', '0721520669', true, true),
  ('Manager Caz Constantin Adina Dgaspc S3', 'Manager Caz', 'adina221@yahoo.com', '0721216812', false, true),
  ('Manta Aura', 'Îngrijitor', 'mantaaura74@gmail.com', '0769584210', true, true),
  ('Marinescu Marilena Madalina', 'ASISTENT MEDICAL GENERALIST', 'madalina198621@gmail.com', '0726726340', true, true),
  ('Matache Iulia', 'Sef centru', 'sibyyuly86@gmail.com', '0786992250', true, true),
  ('Mihăilă Irina', 'Îngrijitor', 'victormihaila56@gmail.com', '0771695353', true, true),
  ('Militaru Alina', 'Infirmieră', 'militarualina15@gmail.com', '0724168947', true, true),
  ('Mincu Steliana', 'Infirmieră', 'mincusteliana@gmail.com', '0756507641', true, true),
  ('Minoiu Mihaela Georgiana', 'Asistent medical generalist', 'mihaelaminoiu4@gmail.com', '0784097007', true, true),
  ('Moraru Marinela', 'Infirmiera', 'morarunela685@gmail.com', '0770947090', true, true),
  ('Munteanu Izabela Daniela', 'Asistent Medical', 'izabelamunteanu95@yahoo.com', '0722641744', true, true),
  ('Munteanu Silviu-Cristian', 'Asistent Social', 'msilviu15@gmail.com', '0751164410', true, true),
  ('Murat Maria Diana', 'Asistent Social', 'muratmariadiana2@gmail.com', '0792276559', true, true),
  ('Musel Mariana Georgeta', 'Infirmieră', 'musel.mariana7@yahoo.com', '0772133117', true, true),
  ('Mustatea Nina Nicolea', 'Asistent medical', 'TESTNICO@GMAIL.COM', NULL, true, true),
  ('Mustățea Ana Maria', 'Terapeut Ocupațional', 'mustateaana72@gmail.com', '0748305746', true, true),
  ('Mîrzac Ana Maria', 'Asistent Medical Generalist', 'testmarzac@gmail.com', '0766014385', true, true),
  ('Neagu Constanta', 'Infirmieră', 'tantaneagu3@gmail.com', '0735599913', true, true),
  ('Neagu Lorena', 'Asistent Social', 'lorineagu43@gmail.com', '0772044621', true, true),
  ('Neatu Felicica', 'INFIRMIERA', 'neatufelicia40@gmail.com', NULL, true, true),
  ('Nechifor Ana', 'INFIRMIERA', 'ionana1971@gmail.com', '0721085799', true, true),
  ('Niculae Valeria', 'Îngrijitor', 'lilivaletina2021@gmail.com', '0764192747', true, true),
  ('Niculici Ildiko', 'Îngrijitor', 'niculiciildico@gmail.com', '0760140973', true, true),
  ('Nistor Dragoș Mihai', 'Asistent social', 'nistordragos12732@gmail.com', '0752332216', true, true),
  ('Nitu George', 'Lucrător Social', 'georgenitu370@gmail.com', '0724062023', true, true),
  ('Ocolea Marioara', 'Infirmieră', 'marioara.ocolea@gmail.com', '0766450458', true, true),
  ('Olteanu Alexandra Emilia', 'Asistent Social', 'andaolteanu2003@gmail.com', '0734849454', true, true),
  ('Olteanu Stefania Andreea', 'Asistent Medical Generalist', 'stefaniaandreea78@gmail.com', '0737485883', true, true),
  ('Oprea Ioana', 'Infirmieră', 'TEST2550331520047@GMAIL.COM', NULL, true, true),
  ('Paduraru Angelica-Vali', 'Asistent Medical Generalist', 'valentinacipi83@gmail.com', '0766245047', true, true),
  ('Paduraru Nina', 'Infirmieră', 'padurarunina56@gmail.com', '0736181928', true, true),
  ('Parpalea Mădălin Ionuț', 'Lucrător Social', 'testmadalin@gmail.com', NULL, true, true),
  ('Pata Florentina Cristina', 'Infirmieră', 'floripata6@gmail.com', '0764750543', true, true),
  ('Pataliu Lenuta', 'Lucrător Social', 'leanapataliu0@gmail.com', '0764662771', true, true),
  ('Patrascu Marius Florin', 'Terapeut Ocupational', 'mariuspatrascumaximus321@gmail.com', '0784677552', true, true),
  ('Peicea Florina', 'Infirmieră', 'floripeicea@gmail.com', '0729644427', true, true),
  ('Pencea Elena', 'Infirmieră', 'TEST2740322520022@GMAIL.COM', NULL, true, true),
  ('Pescaru Ilinca Dgaspc S2', 'Inspector', 'ilinca_pescaru@yahoo.com', '0733932117', false, true),
  ('Petcu Nicoleta-Catalina', 'Infirmieră', 'petcunicoleta0@gmail.com', '0734523590', true, true),
  ('Petraru Alina Ionela', 'Îngrijitoare la Unitățile de Ocrotire Socială și Sanitară', 'alinapetraru13@gmail.com', '0731967005', true, true),
  ('Petrescu Milena', 'Terapeut ocupațional', 'milenapetrescu@yahoo.com', '0770263103', true, true),
  ('Pintilie Olimpia', 'Infirmieră', 'pintiliedany17@gmail.com', '0763983114', true, true),
  ('Popa Alin', 'Lucrător Social', 'TESTPOPAALIN@GMAIL.COM', NULL, true, true),
  ('Popa Ilie Cristian', 'Lucrător Social', 'iliecristianpopa@gmail.com', '0711087627', true, true),
  ('Popa Istina', 'Infirmieră', 'popaistina@yahoo.com', '0760924891', true, true),
  ('Popa Mihai', 'Lucrător Social', 'silviupopa969@gmail.com', '0732771767', true, true),
  ('Popescu Nina', 'Asistent Medical Generalist', 'ninapopescu303@gmail.com', '0727264560', true, true),
  ('Postolache Maria Cristina', 'Asistent Social', 'postolachee_mariaa@yahoo.com', '0755733269', true, true),
  ('Pușcoiu Florin Cosmin', 'Lucrător Social', 'cosminpuscoiu18@gmail.com', '0763113441', true, true),
  ('Pînzaru-Braharu Mariana', 'Infirmieră', 'pinzarubraharumariana@gmail.com', '0727331026', true, true),
  ('Pătrașcu Mirela Nicoleta', 'Terapeut Ocupational', 'mirelanicoletapatrascu@gmail.com', '0760809829', true, true),
  ('Radulescu Dori', 'Tehnician Asistent Social', 'myjully1990@gmail.com', '0793392147', true, true),
  ('Soare Denisa Maia', 'Îngrijitor', 'denisamaia390@gmail.com', '0760736364', true, true),
  ('Soare Iuliana', 'Infirmieră', 'soareiuliana926@gmailcom', '0729733169', true, true),
  ('Spiridon Manuela', 'Infirmiera', 'spiridonmanuela@gmail.com', '0731438309', true, true),
  ('Staicu Marusia', 'Șef Centru', 'staicumarusia7@gmail.com', '0788264178', true, true),
  ('Stan Ioana Maria', 'Infirmieră', 'ioanastanlili@gmail.com', '0766063203', true, true),
  ('Stan Mariana', 'Infirmieră', 'marianastan886@gmail.com', '0733378592', true, true),
  ('Stanciu Eleonora Dgaspc Gorj', 'Psiholog', 'stanciu.eleonora@yahoo.com', '0785237746', false, true),
  ('State Felicia', 'Asistent Medical Generalist', 'feliciastate980@gmail.com', '0765489099', true, true),
  ('Stefan Andreea Ioana', 'Îngrijitoare la Unitățile de Ocrotire Socială și Sanitară', 'andreeavasile104@gmail.com', '0768302602', true, true),
  ('Stefan Petruta', 'Ajutor Bucătar', 'petrutastefan77@gmail.com', '0730748998', true, true),
  ('Stoica Cristina Ioana', 'Asistent Medical Generalist', 'cristiina.ioana@yahoo.com', '0767967086', true, true),
  ('Stoica Marius Filip', 'Lucrător Social', 'marius.stoica202007@gmail.com', '0790447478', true, true),
  ('Stoica Teodora', 'Infirmieră', 'stoicateodora896@gmail.com', '0792291904', true, true),
  ('Stănescu Manuela Isabela', 'Asistent Social', 'manuelastanescu0111@gmail.com', '0737914675', true, true),
  ('Sîrbu Marian', 'Lucrator social', 'mariansirbu09@yahoo.com', '072211688', true, true),
  ('Tatu Ana Maria', 'Asistent Medical Generalist', 'razvantatu21@gmail.com', '0733098587', true, true),
  ('Teofil Anastasia Theodora', 'Sef Centru, asistent Social', 'anastasia.teofil@yahoo.com', '0726516578', true, true),
  ('Test Account', 'Admin', 'test@hotmail.com', '12312321', true, true),
  ('Timar Mihaela Iuliana', 'Asistent Medical Generalist', 'timarmihaela35@gmail.com', '0766248106', true, true),
  ('Tolea Maria', 'Psiholog', 'toleamaria@yahoo.com', '0729154584', true, true),
  ('Topala Mariana Denisa', 'Terapeut Ocupațional', 'topaladenisa1@gmail.com', '0765419178', false, true),
  ('Trocan Roxana Nicoleta', 'Asistent Medical Generalist', 'nroxana970@gmail.com', '0756959474', true, true),
  ('Ulea Elena', 'Infirmieră', 'testulea@gmail.com', '0722480043', true, true),
  ('Ungureanu Alexia', 'contabil', 'alexiamarriaungureanu@yahoo.com', '0772236265', true, true),
  ('Ungureanu Marian', 'Psiholog', 'marianungureanu2009@gmail.com', NULL, true, true),
  ('Ungureanu Silvia', 'Asistent social', 'silviaungureanu75@gmail.com', '0771336338', true, true),
  ('Ungureanu Stefan Leonard', 'MENTENANTA', 'stefanleonardd@gmail.com', '0773779422', true, true),
  ('Vaduva Buzatu Silvia', 'ASISTENT MEDICAL GENERALIST', 'svaduva.066@gmail.com', '0736647186', true, true),
  ('Vasilescu Ioana', 'Infirmieră', 'TESTVASILESCUIOANA@GMAIL.COM', NULL, true, true),
  ('Velicu Marilena Mirela', 'Infirmieră', 'velicumirela74@yahoo.com', '0763663310', true, true),
  ('Velicu Mirela', 'Infirmieră', 'mirelavelicu48@gmail.com', '0734272012', true, true),
  ('Velicu Silvia Monica', 'Asistent Medical Generalist', 'velicumonika@gmail.com', '0765138107', true, true),
  ('Vilcan Doinita', 'Asistent medical generalist', 'doinitaalina02@gmail.com', '0767557045', true, true),
  ('Visan Gratiela Ioana', 'Ergoterapeut', 'visangratiela26@gmail.com', '0728756133', true, true),
  ('Voicilă Andra Roxana', 'Terapeut Ocupațional', 'voicila.andra.ro@gmail.com', '0774097146', false, true),
  ('Voicilă Elena', 'Gestionar', 'evoicila120@gmail.com', '0785513884', true, true),
  ('Voicu Niculina', 'Infirmieră', 'nicoletav458@gmail.com', '0768468700', true, true),
  ('Voicu Tudorița', 'Infirmieră', 'tudoritavoicu35@gmail.com', '0720383260', true, true),
  ('Văduva Petruța', 'Infirmiera', 'petrutavaduva482@gmail.com', '0736483275', true, true),
  ('Zamfir Mihaela', 'Îngrijitor', 'zamfir@gmail.com', '0734802080', true, true),
  ('Zgorobete Daniela', 'Infirmieră', 'TEST26901135200351@GMAIL.COM', NULL, true, true),
  ('Ștefan Maria-Ștefania', 'Kinetoterapeut', 'stefanmariastefania7@gmail.com', '0783064709', true, true)
on conflict (nume) do nothing;

-- Legaturi angajat <-> centru (centrul principal + centrele suplimentare unde e administrator)
-- Potrivim angajatul dupa (nume, email) si centrul dupa nume, ca sa evitam sa scriem UUID-uri manual.
insert into public.employee_centers (employee_id, center_id)
select e.id, c.id
from (values
  ('Alan Altonchi', 'alanaltonchi@hotmail.com', 'Test Center'),
  ('Andreescu Andrei-Vlad', 'andreescuandrei190@gmail.com', 'CZ Mihai Bravu'),
  ('Andreescu Cristina Firma Contabila', 'cristinaangelaandreescu2003@gmail.com', 'SAS Mihai Bravu'),
  ('Argeșeanu Cristina Georgiana', 'cristinaargeseanu.ca@gmail.com', 'CIA Casa cu Tei'),
  ('Arsene Elena', 'testarsene@gmail.com', 'CABR Argedava'),
  ('Badea Andreea Luciana', 'lucianabadea75@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Badea Danut', 'testbadea@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Badea Laurentia Cristiana', 'badeamaria420@gmail.com', 'LMP Mihai Bravu 416'),
  ('Banu Niculaie', 'banuniculaie64@gmail.com', 'CIA Romantic'),
  ('Barb-Dudan Felicia-Sector 3', 'f.georgiana23@yahoo.com', 'CIA Casa cu Tei'),
  ('Barb-Dudan Felicia-Sector 3', 'f.georgiana23@yahoo.com', 'CIA Romantic'),
  ('Belghiru Roxana', 'roxanabelghiru@gmail.com', 'CIA Romantic'),
  ('Bici Maria', 'bicimariana128@gmail.com', 'CIA Romantic'),
  ('Blănaru Alin Cristian', 'alincristian1201@gmail.com', 'CZ Mihai Bravu'),
  ('Bogdan Marian-Viorel', 'mariantest@gmail.com', 'LMP Pantelimon 1'),
  ('Boșman Petronela', 'petronelabosman@gmail.com', 'CABR Argedava'),
  ('Burcea Gabriela', 'burceagabriela43@gmail.com', 'CIA Romantic'),
  ('Burtavel Ionel', 'ionelburtavel20@gmail.com', 'CABR Argedava'),
  ('Buzică Doinița', 'buzicadoinita1@gmail.com', 'SID Vârstnici'),
  ('Bîrlan Viorica', 'birlanviorica@gmail.com', 'CIA Casa cu Tei'),
  ('Caimacanu Leana Iuliana', 'liliana@gmail.com', 'LMP Mihai Bravu 104'),
  ('Calea Catalin Ionut', 'calea7@gmail.com', 'SID Vârstnici'),
  ('Calin Rodica', 'rodicacalin2017@gmail.com', 'LMP Pantelimon 1'),
  ('Chiripuci Constanta', 'chiripucitanta@gmail.com', 'CIA Casa cu Tei'),
  ('Chițu Gabriela-Raluca', 'ralucachitu1214@gmail.com', 'ALEX SOCIAL'),
  ('Ciocan Mihaela', 'miki27031968@gmail.com', 'CIA Casa cu Tei'),
  ('Ciocoiu Elena Florenta', 'elenaflorentaciocoiu@gmail.com', 'CIA Romantic'),
  ('Cirstea Elena Georgiana', 'cridfllo@gmail.com', 'CZ Mihai Bravu'),
  ('Ciulei Mitana Niculina', 'ciulei@gmail.com', 'LMP Mihai Bravu 209'),
  ('Ciumber Steluța', 'ciumbersteluta06@gmail.com', 'CIA Casa cu Tei'),
  ('Claudia Ungureanu', 'caminromanticclub@gmail.com', 'CIA Casa cu Tei'),
  ('Constantin Elena Cristina', 'elenacristina2112@gmail.com', 'CZ Mihai Bravu'),
  ('Cosoi Iuliana Valentina', 'iulianacosoi@gmail.com', 'CZ Mihai Bravu'),
  ('Cosovliu Nicoleta', 'ncosovliu@gmail.com', 'CIA Romantic'),
  ('Costache Gabriel', 'TESTCOSTACHEGABRIEL@GMAIL.COM', 'LMP 1 Ateneul Roman'),
  ('Costache Gabriel', 'TESTCOSTACHEGABRIEL@GMAIL.COM', 'CZ Mihai Bravu'),
  ('Costache Gabriel', 'TESTCOSTACHEGABRIEL@GMAIL.COM', 'LMP Mihai Bravu 303N'),
  ('Creangă Nicoleta Cristina', 'cristinacreanga499@yahoo.com', 'CZ Mihai Bravu'),
  ('Crețu Constantin', 'valicretu66@gmail.com', 'CIA Casa cu Tei'),
  ('Crețu Irina', 'irinacretu591@gmail.com', 'LMP Mihai Bravu 309'),
  ('Căpitanu Mariana Nicoleta', 'capitanumariana903@gmail.com', 'LMP Mihai Bravu 101'),
  ('Daia Gina', 'daiagina71@gmail.com', 'CIA Romantic'),
  ('Debretin Denisa', 'karinna2924@gmail.com', 'CIA Romantic'),
  ('Dinu Daniela Ionela', 'voineadaniela2010@gmail.com', 'LMP Pantelimon 2'),
  ('Dinu Georgeta', 'georgetadinu906@gmail.com', 'CABR Argedava'),
  ('Dinulescu Ileana', 'ileanadinulescu71@gmail.com', 'CIA Romantic'),
  ('Dogaru Alexandra Denisa', 'alexandra.dogaru12@gmail.com', 'SID Vârstnici'),
  ('Draganescu Cristina Mirela', 'Bvy05920@gmail.com', 'CIA Romantic'),
  ('Draghia Liliana', 'bogdanbrotacel@gmail.com', 'CIA Romantic'),
  ('Dragomir Iuliana Arabela', 'iulianadragomir478@gmail.com', 'CIA Casa cu Tei'),
  ('Drăgănescu Cristian', 'bxc5599@gmail.com', 'CABR Argedava'),
  ('Dumitrache Doru', 'dumitrachetest@gmail.com', 'LMP Pantelimon 2'),
  ('Dumitru Doina', 'enacheilona13@gmail.com', 'CZ Mihai Bravu'),
  ('Dumitru Ilie', 'id080511@gmail.com', 'CIA Casa cu Tei'),
  ('Dumitru Marius Alin', 'alinm9429@gmail.com', 'CIA Casa cu Tei'),
  ('Dumitru Smaranda Marcela', 'dumitrusmarandamarcela@gmail.com', 'CIA Casa cu Tei'),
  ('Ene Anișoara', 'eneanisoara5@gmail.com', 'CABR Argedava'),
  ('Ene Daniela', 'danielapietris1@gmail.com', 'CZ Mihai Bravu'),
  ('Enus Mihai', 'mihaitaenus95@gmail.com', 'CABR Argedava'),
  ('Florescu Cristina', 'cristinabolboasa8@gmail.com', 'CABR Argedava'),
  ('Friptu Doina', 'doinafriptu869@gmail.com', 'CIA Casa cu Tei'),
  ('Friptu Fanel', 'friptufane16@gmail.com', 'CIA Casa cu Tei'),
  ('Friptu Georgiana Denisa', 'friptumirel@yahoo.com', 'LMP Mihai Bravu 416'),
  ('Friptu Marius Bogdan', 'friptumarius1410@gmail.com', 'CABR Argedava'),
  ('Făinaru Anișoara', 'anisoarafainaru@gmail.com', 'SID Vârstnici'),
  ('Garaliu Andreea', 'garaliuandreea70@gmail.com', 'SID Vârstnici'),
  ('Gheorghe Remus', 'gheorghetest@gmail.com', 'LMP Pantelimon 1'),
  ('Gherasim Violeta', 'gherasimvioleta1111@gmail.com', 'CIA Casa cu Tei'),
  ('Ghiulea Petra', 'ghiulea.petra@gmail.com', 'CIA Casa cu Tei'),
  ('Grama Adriana', 'adrianagrama667@gmail.com', 'CABR Argedava'),
  ('Graure Alexandra', 'alexaagraure@gmail.com', 'CABR Argedava'),
  ('Grindean Elena Camelia', 'elenacameliagrindean3@gmail.com', 'CIA Casa cu Tei'),
  ('Gudină Maria', 'gudina.maria68@gmail.com', 'CIA Casa cu Tei'),
  ('Iancu Georgiana-Marina', 'georgianamarina35@gmail.com', 'CABR Argedava'),
  ('Iancu Ionut', 'ionutiancu19866@gmail.com', 'CIA Casa cu Tei'),
  ('Iofcea Maria', 'iofceamariamagdalena@gmail.com', 'CIA Romantic'),
  ('Iofcea Valentin', 'iofceatest@gmail.com', 'CIA Romantic'),
  ('Ion Alexandra Florentina', 'ionalexandra645@gmail.com', 'CIA Romantic'),
  ('Ion Florina', 'florina.ivan2226@gmail.com', 'SID Vârstnici'),
  ('Ion Nuti Geanina', 'Iongeanina969@gmail.com', 'CIA Casa cu Tei'),
  ('Ivan Aurica', 'ivan@gmail.com', 'LMP Pantelimon 4'),
  ('Ivan Grațiela Elena', 'gratiela11ivan@gmail.com', 'LMP Mihai Bravu 416'),
  ('Leană Ionela', 'danielaileana221@gmail.com', 'CIA Casa cu Tei'),
  ('Lemăndroi Mihai', 'mihai01lemandroi@gmail.com', 'LMP Mihai Bravu 303'),
  ('Lepădatu Alexandra', 'lepadatusanda815@gmail.com', 'LMP Mihai Bravu 201'),
  ('Lincu Gabriela Elena', 'lincugabrielaelena@gmail.com', 'CIA Casa cu Tei'),
  ('Lincu Gabriela Elena', 'lincugabrielaelena@gmail.com', 'CIA Romantic'),
  ('Lupu Catalin', 'lupucatalin08@gmail.com', 'CIA Casa cu Tei'),
  ('Lăcătușu Mihaela', 'vanessa.maria231998@gmail.com', 'LMP Pantelimon 1'),
  ('Macavei Floarea', 'mfloarea676@gmail.com', 'CIA Casa cu Tei'),
  ('Manager Caz Constantin Adina Dgaspc S3', 'adina221@yahoo.com', 'LMP 1 Ateneul Roman'),
  ('Manta Aura', 'mantaaura74@gmail.com', 'SID Vârstnici'),
  ('Marinescu Marilena Madalina', 'madalina198621@gmail.com', 'CIA Casa cu Tei'),
  ('Marinescu Marilena Madalina', 'madalina198621@gmail.com', 'LMP Stefan cel Mare'),
  ('Marinescu Marilena Madalina', 'madalina198621@gmail.com', 'CZ Mihai Bravu'),
  ('Matache Iulia', 'sibyyuly86@gmail.com', 'LMP Pantelimon 2'),
  ('Mihăilă Irina', 'victormihaila56@gmail.com', 'CIA Romantic'),
  ('Militaru Alina', 'militarualina15@gmail.com', 'CIA Casa cu Tei'),
  ('Mincu Steliana', 'mincusteliana@gmail.com', 'CABR Argedava'),
  ('Minoiu Mihaela Georgiana', 'mihaelaminoiu4@gmail.com', 'CIA Casa cu Tei'),
  ('Moraru Marinela', 'morarunela685@gmail.com', 'CIA Casa cu Tei'),
  ('Munteanu Izabela Daniela', 'izabelamunteanu95@yahoo.com', 'LMP Mihai Bravu 305'),
  ('Munteanu Silviu-Cristian', 'msilviu15@gmail.com', 'LMP Mihai Bravu 303'),
  ('Murat Maria Diana', 'muratmariadiana2@gmail.com', 'CZ Mihai Bravu'),
  ('Musel Mariana Georgeta', 'musel.mariana7@yahoo.com', 'LMP Mihai Bravu 305'),
  ('Mustatea Nina Nicolea', 'TESTNICO@GMAIL.COM', 'LMP Pantelimon 1'),
  ('Mustățea Ana Maria', 'mustateaana72@gmail.com', 'CZ Mihai Bravu'),
  ('Mîrzac Ana Maria', 'testmarzac@gmail.com', 'LMP Mihai Bravu 209'),
  ('Neagu Constanta', 'tantaneagu3@gmail.com', 'CABR Argedava'),
  ('Neagu Lorena', 'lorineagu43@gmail.com', 'CZ Mihai Bravu'),
  ('Neatu Felicica', 'neatufelicia40@gmail.com', 'LMP Mihai Bravu 101'),
  ('Nechifor Ana', 'ionana1971@gmail.com', 'LMP Mihai Bravu 416'),
  ('Niculae Valeria', 'lilivaletina2021@gmail.com', 'CABR Argedava'),
  ('Niculici Ildiko', 'niculiciildico@gmail.com', 'SID Vârstnici'),
  ('Niculici Ildiko', 'niculiciildico@gmail.com', 'EM Mihai Bravu'),
  ('Nistor Dragoș Mihai', 'nistordragos12732@gmail.com', 'LMP Pantelimon 1'),
  ('Nitu George', 'georgenitu370@gmail.com', 'CIA Romantic'),
  ('Ocolea Marioara', 'marioara.ocolea@gmail.com', 'CIA Casa cu Tei'),
  ('Olteanu Alexandra Emilia', 'andaolteanu2003@gmail.com', 'CZ Mihai Bravu'),
  ('Olteanu Stefania Andreea', 'stefaniaandreea78@gmail.com', 'CIA Romantic'),
  ('Oprea Ioana', 'TEST2550331520047@GMAIL.COM', 'CIA Romantic'),
  ('Paduraru Angelica-Vali', 'valentinacipi83@gmail.com', 'CABR Argedava'),
  ('Paduraru Nina', 'padurarunina56@gmail.com', 'CABR Argedava'),
  ('Parpalea Mădălin Ionuț', 'testmadalin@gmail.com', 'CIA Romantic'),
  ('Pata Florentina Cristina', 'floripata6@gmail.com', 'CIA Casa cu Tei'),
  ('Pataliu Lenuta', 'leanapataliu0@gmail.com', 'CIA Romantic'),
  ('Patrascu Marius Florin', 'mariuspatrascumaximus321@gmail.com', 'CIA Romantic'),
  ('Peicea Florina', 'floripeicea@gmail.com', 'CABR Argedava'),
  ('Pencea Elena', 'TEST2740322520022@GMAIL.COM', 'CIA Romantic'),
  ('Petcu Nicoleta-Catalina', 'petcunicoleta0@gmail.com', 'CIA Casa cu Tei'),
  ('Petraru Alina Ionela', 'alinapetraru13@gmail.com', 'SID Vârstnici'),
  ('Petrescu Milena', 'milenapetrescu@yahoo.com', 'CZ Mihai Bravu'),
  ('Pintilie Olimpia', 'pintiliedany17@gmail.com', 'CIA Romantic'),
  ('Popa Alin', 'TESTPOPAALIN@GMAIL.COM', 'CIA Romantic'),
  ('Popa Ilie Cristian', 'iliecristianpopa@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Popa Istina', 'popaistina@yahoo.com', 'LMP 1 Ateneul Roman'),
  ('Popa Mihai', 'silviupopa969@gmail.com', 'CIA Romantic'),
  ('Popescu Nina', 'ninapopescu303@gmail.com', 'CIA Casa cu Tei'),
  ('Postolache Maria Cristina', 'postolachee_mariaa@yahoo.com', 'CZ Mihai Bravu'),
  ('Pușcoiu Florin Cosmin', 'cosminpuscoiu18@gmail.com', 'CIA Romantic'),
  ('Pînzaru-Braharu Mariana', 'pinzarubraharumariana@gmail.com', 'CIA Casa cu Tei'),
  ('Pătrașcu Mirela Nicoleta', 'mirelanicoletapatrascu@gmail.com', 'CIA Romantic'),
  ('Pătrașcu Mirela Nicoleta', 'mirelanicoletapatrascu@gmail.com', 'CABR Argedava'),
  ('Radulescu Dori', 'myjully1990@gmail.com', 'CABR Argedava'),
  ('Soare Denisa Maia', 'denisamaia390@gmail.com', 'CIA Romantic'),
  ('Soare Iuliana', 'soareiuliana926@gmailcom', 'CIA Casa cu Tei'),
  ('Spiridon Manuela', 'spiridonmanuela@gmail.com', 'LMP Pantelimon 1'),
  ('Spiridon Manuela', 'spiridonmanuela@gmail.com', 'CIA Casa cu Tei'),
  ('Staicu Marusia', 'staicumarusia7@gmail.com', 'CIA Casa cu Tei'),
  ('Stan Ioana Maria', 'ioanastanlili@gmail.com', 'LMP Mihai Bravu 104'),
  ('Stan Mariana', 'marianastan886@gmail.com', 'CIA Casa cu Tei'),
  ('State Felicia', 'feliciastate980@gmail.com', 'CABR Argedava'),
  ('Stefan Andreea Ioana', 'andreeavasile104@gmail.com', 'SID Vârstnici'),
  ('Stefan Petruta', 'petrutastefan77@gmail.com', 'CIA Casa cu Tei'),
  ('Stoica Cristina Ioana', 'cristiina.ioana@yahoo.com', 'LMP Pantelimon 4'),
  ('Stoica Marius Filip', 'marius.stoica202007@gmail.com', 'CIA Casa cu Tei'),
  ('Stoica Teodora', 'stoicateodora896@gmail.com', 'CIA Romantic'),
  ('Stănescu Manuela Isabela', 'manuelastanescu0111@gmail.com', 'CZ Mihai Bravu'),
  ('Sîrbu Marian', 'mariansirbu09@yahoo.com', 'LMP Mihai Bravu 305'),
  ('Tatu Ana Maria', 'razvantatu21@gmail.com', 'CABR Argedava'),
  ('Teofil Anastasia Theodora', 'anastasia.teofil@yahoo.com', 'CZ Mihai Bravu'),
  ('Test Account', 'test@hotmail.com', 'Test Center'),
  ('Timar Mihaela Iuliana', 'timarmihaela35@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Tolea Maria', 'toleamaria@yahoo.com', 'CZ Mihai Bravu'),
  ('Topala Mariana Denisa', 'topaladenisa1@gmail.com', 'CIA Casa cu Tei'),
  ('Trocan Roxana Nicoleta', 'nroxana970@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Ulea Elena', 'testulea@gmail.com', 'LMP Pantelimon 2'),
  ('Ungureanu Alexia', 'alexiamarriaungureanu@yahoo.com', 'CIA Casa cu Tei'),
  ('Ungureanu Marian', 'marianungureanu2009@gmail.com', 'CABR Argedava'),
  ('Ungureanu Marian', 'marianungureanu2009@gmail.com', 'CIA Romantic'),
  ('Ungureanu Marian', 'marianungureanu2009@gmail.com', 'CIA Casa cu Tei'),
  ('Ungureanu Silvia', 'silviaungureanu75@gmail.com', 'CIA Romantic'),
  ('Ungureanu Stefan Leonard', 'stefanleonardd@gmail.com', 'CIA Casa cu Tei'),
  ('Vaduva Buzatu Silvia', 'svaduva.066@gmail.com', 'CIA Romantic'),
  ('Vasilescu Ioana', 'TESTVASILESCUIOANA@GMAIL.COM', 'LMP Pantelimon 4'),
  ('Velicu Marilena Mirela', 'velicumirela74@yahoo.com', 'LMP Mihai Bravu 303'),
  ('Velicu Mirela', 'mirelavelicu48@gmail.com', 'LMP 1 Ateneul Roman'),
  ('Velicu Silvia Monica', 'velicumonika@gmail.com', 'LMP Mihai Bravu 104'),
  ('Vilcan Doinita', 'doinitaalina02@gmail.com', 'CIA Romantic'),
  ('Visan Gratiela Ioana', 'visangratiela26@gmail.com', 'CZ Mihai Bravu'),
  ('Voicilă Andra Roxana', 'voicila.andra.ro@gmail.com', 'CIA Casa cu Tei'),
  ('Voicilă Elena', 'evoicila120@gmail.com', 'CIA Casa cu Tei'),
  ('Voicu Niculina', 'nicoletav458@gmail.com', 'CIA Romantic'),
  ('Voicu Tudorița', 'tudoritavoicu35@gmail.com', 'CIA Casa cu Tei'),
  ('Văduva Petruța', 'petrutavaduva482@gmail.com', 'CIA Casa cu Tei'),
  ('Zamfir Mihaela', 'zamfir@gmail.com', 'SID Vârstnici'),
  ('Zgorobete Daniela', 'TEST26901135200351@GMAIL.COM', 'CIA Romantic'),
  ('Ștefan Maria-Ștefania', 'stefanmariastefania7@gmail.com', 'CZ Mihai Bravu')
) as v(nume, email, centru)
join public.employees e on e.nume = v.nume and (e.email = v.email or (e.email is null and v.email is null))
join public.centers c on c.nume = v.centru
on conflict do nothing;
